apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: area2
spec:
  project: default
  source:
    path: area2
    repoURL: https://github.com/pacoguzman/gitops-acme
  destination:
    namespace: area2
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
