apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-2
  namespace: rollouts-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollouts-2
  template:
    metadata:
      labels:
        app: rollouts-2
    spec:
      containers:
        - name: rollouts-2
          image: argoproj/rollouts-demo:blue
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
            limits:
              memory: 64Mi
              cpu: 50m
