apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
spec:
  project: default
  source:
    path: area1/team1/backstage/prod
    repoURL: https://github.com/pacoguzman/gitops-acme
  destination:
    namespace: backstage
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
