apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-config
  namespace: backstage
data:
  app-config.prod.yaml: |
    app:
      title: Stuart Developer Portal
      baseUrl: ${BACKSTAGE_URL}

    backend:
      baseUrl: ${BACKSTAGE_URL}
      listen:
        port: 7007
      cors:
        origin: ${BACKSTAGE_URL}
      database:
        client: pg
        connection:
          host: ${BACKSTAGE_POSTGRES_HOST}
          port: ${BACKSTAGE_POSTGRES_SERVICE_PORT}
          user: ${POSTGRES_USER}
          password: ${POSTGRES_PASSWORD}

    techdocs:
      storageUrl: ${BACKSTAGE_URL}/api/techdocs/static/docs
      requestUrl: ${BACKSTAGE_URL}/api/techdocs

    cache:
      store: redis
      connection: ${BACKSTAGE_REDIS_CONNECTION}

    catalog:
      import:
        entityFilename: catalog-info.yaml
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [Component, System, API, Group, User, Resource, Location]
      locations:
        # dev-portal it self (to be removed after setting up integration I guess)
        - type: file
          target: /app/catalog-info.yaml
