apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  #- postgres-sealedsecret.yaml
  - postgres-storage.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - redis-cache-statefulset.yaml
  - redis-cache-service.yaml
  #- sealedsecret.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namespace: backstage
