apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts
  namespace: rollouts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollouts
  template:
    metadata:
      labels:
        app: rollouts
    spec:
      containers:
        - name: rollouts
          image: argoproj/rollouts-demo:blue
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources: {}

