apiVersion: v1
kind: Service
metadata:
  name: rollouts
  namespace: rollouts
  annotations:
    foo: bar
spec:
  selector:
    app: rollouts
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
